### ISSUE TITLE
Error not caught when purchasing 

### ISSUE THREAD

**Issue by opensourcegps** [dooboolab/flutter_inapp_purchase#10]
Some testing results, version 0.5.2. There is a crash when there is error on purchasing.

````
 try {

        _purchase_data = await FlutterInappPurchase.buyProduct(_product_id);

        print('purcuased - ${_purchase_data.toString()}');

        //getting transaction data - todo


    } catch (error) {

        print('$error');

    }
````

In case product was already purchased, error is not caught.

````
W/BillingClient(23589): Unable to buy item, Error response code: 7
D/InappPurchasePlugin(23589): Purchase Updated Listener
D/InappPurchasePlugin(23589): responseCode: 7
E/MethodChannel#flutter_inapp(23589): Failed to handle method call
E/MethodChannel#flutter_inapp(23589): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#flutter_inapp(23589): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:162)
E/MethodChannel#flutter_inapp(23589): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:199)
E/MethodChannel#flutter_inapp(23589): 	at com.dooboolab.flutterinapppurchase.FlutterInappPurchasePlugin.onMethodCall(FlutterInappPurchasePlugin.java:348)
E/MethodChannel#flutter_inapp(23589): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter_inapp(23589): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/MethodChannel#flutter_inapp(23589): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_inapp(23589): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#flutter_inapp(23589): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#flutter_inapp(23589): 	at android.app.ActivityThread.main(ActivityThread.java:7377)
E/MethodChannel#flutter_inapp(23589): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_inapp(23589): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
E/MethodChannel#flutter_inapp(23589): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
E/FlutterNativeView(23589): Uncaught exception in binary message listener
E/FlutterNativeView(23589): java.lang.IllegalStateException: Reply already submitted
E/FlutterNativeView(23589): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:162)
E/FlutterNativeView(23589): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:209)
E/FlutterNativeView(23589): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/FlutterNativeView(23589): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterNativeView(23589): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/FlutterNativeView(23589): 	at android.os.Looper.loop(Looper.java:144)
E/FlutterNativeView(23589): 	at android.app.ActivityThread.main(ActivityThread.java:7377)
E/FlutterNativeView(23589): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterNativeView(23589): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
E/FlutterNativeView(23589): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
V/AudioManager(23589): playSoundEffect   effectType: 0
I/flutter (23589): PlatformException(InappPurchasePlugin, purchase error, responseCode: 7)
````

catch (error) should work and say product was already purchased. Not a critical issue and easy to workaround, but just FYI.

**Comment by dooboolab** [comment]
@opensourcegps Is this crashing?

**Comment by opensourcegps** [comment]
Actually everything works after this and probably "catch" works, however you see those scary messages from native side.

**Comment by dooboolab** [comment]
@opensourcegps That is exactly the same message that IAP module is throwing in android when `catch`. This is just to give `deverloper` an info and not appearing in the user side.

Thank you for the issue. However, will leave it for now and closing it.
