### ISSUE TITLE
App crashes when paying with 'Slow test card, approves after a few minutes.' 

### ISSUE THREAD

**Issue by dipinarora9** [dooboolab/flutter_inapp_purchase#102]
### Version of flutter_inapp_purchase - 2.0.0+11

Problem being faced on a physical android device.

### Actual behavior
App just crashes giving the following output.

```
E/DoobooUtils(21252): Error Code : 5
D/AndroidRuntime(21252): Shutting down VM
E/AndroidRuntime(21252): FATAL EXCEPTION: main
E/AndroidRuntime(21252): Process: dipinarora9.IncomeTaxCalculator, PID: 21252
E/AndroidRuntime(21252): java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.String;@430907d
E/AndroidRuntime(21252): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/AndroidRuntime(21252): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/AndroidRuntime(21252): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/AndroidRuntime(21252): 	at com.dooboolab.flutterinapppurchase.AndroidInappPurchasePlugin$5.onAcknowledgePurchaseResponse(AndroidInappPurchasePlugin.java:408)
E/AndroidRuntime(21252): 	at com.android.billingclient.api.BillingClientImpl$18$2.run(BillingClientImpl.java:1117)
E/AndroidRuntime(21252): 	at android.os.Handler.handleCallback(Handler.java:815)
E/AndroidRuntime(21252): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime(21252): 	at android.os.Looper.loop(Looper.java:207)
E/AndroidRuntime(21252): 	at android.app.ActivityThread.main(ActivityThread.java:5769)
E/AndroidRuntime(21252): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21252): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(21252): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

### Steps to reproduce the behavior

When requesting for a test purchase instead of selecting 'Test card, always approves' try selecting 'Slow test card, approves after a few minutes.'.

**Comment by hyochan** [comment]
Hey, I've just tested now and flutter seems to only send `string` as a parameter. I've release 2.0.0+12 for the fix. Please try and come back.

**Comment by dipinarora9** [comment]
hey again @hyochan ! **The issue seems to be fixed now.** App is not crashing and I am getting the required Platform exception for acknowledgement of purchase.

### Thanks again!

**Comment by hyochan** [comment]
My pleasure!
