### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by lukepighetti** [dooboolab/flutter_inapp_purchase#11]
I am not sure what caused this. Just passing it on.

```
  (11443): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[21,tid=11493,Native,Thread*=0xb88687d0,peer=0x132ff0a0,"Thread-15188"]
E/ActivityThread(11443): Activity com.ifthen.whencoin.MainActivity has leaked ServiceConnection com.dooboolab.flutterinapppurchase.FlutterInappPurchasePlugin$1@3cef2495 that was originally bound here
E/ActivityThread(11443): android.app.ServiceConnectionLeaked: Activity com.ifthen.whencoin.MainActivity has leaked ServiceConnection com.dooboolab.flutterinapppurchase.FlutterInappPurchasePlugin$1@3cef2495 that was originally bound here
E/ActivityThread(11443): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1255)
E/ActivityThread(11443): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1149)
E/ActivityThread(11443): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1937)
E/ActivityThread(11443): 	at android.app.ContextImpl.bindService(ContextImpl.java:1920)
E/ActivityThread(11443): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
E/ActivityThread(11443): 	at com.dooboolab.flutterinapppurchase.FlutterInappPurchasePlugin.onMethodCall(FlutterInappPurchasePlugin.java:87)
E/ActivityThread(11443): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/ActivityThread(11443): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/ActivityThread(11443): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/ActivityThread(11443): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/ActivityThread(11443): 	at android.os.Looper.loop(Looper.java:122)
E/ActivityThread(11443): 	at android.app.ActivityThread.main(ActivityThread.java:5422)
E/ActivityThread(11443): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(11443): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ActivityThread(11443): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
E/ActivityThread(11443): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
D/ConnectivityManager.CallbackHandler(11443): CM callback handler got msg 524296
Lost connection to device.
```

excerpt
```
com.dooboolab.flutterinapppurchase.FlutterInappPurchasePlugin.onMethodCall(FlutterInappPurchasePlugin.java:87)
```

**Comment by lukepighetti** [comment]
I'm reluctant to say anything because I don't know if it's correlated, but this was happening while entering and exiting webviews really quickly using `url_launcher` with `forceWebView: true`

**Comment by dooboolab** [comment]
@lukepighetti Did you use `endConnection` method when you finished using purchase service?

**Comment by lukepighetti** [comment]
I did not!

**Comment by dooboolab** [comment]
<img width="905" alt="screen shot 2018-08-11 at 7 48 15 am" src="https://user-images.githubusercontent.com/27461460/43984347-f467ac4e-9d3a-11e8-980c-41fc0ae5d8c9.png">
Above process is needed in android.
