### ISSUE TITLE
getSkuDetails() failed. Response code: 6

### ISSUE THREAD

**Issue by ukeOnFire** [dooboolab/flutter_inapp_purchase#125]
I tried with both, my app and the in plugin included example project, and both return the error message below.

`I/flutter (12215): ---------- Get Items Button Pressed
W/BillingClient(12215): getSkuDetails() failed. Response code: 6
E/DoobooUtils(12215): Error Code : 6
E/flutter (12215): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(getItemsByType, E_UNKNOWN, An unknown or unexpected error has occured. Please try again later.)
E/flutter (12215): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (12215): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (12215): <asynchronous suspension>
E/flutter (12215): #2      FlutterInappPurchase.getProducts (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:103:39)
E/flutter (12215): #3      _InAppState._getProduct (package:flutter_inapp_purchase_example/main.dart:109:63)
E/flutter (12215): #4      _InAppState.build.<anonymous closure> (package:flutter_inapp_purchase_example/main.dart:314:38)
E/flutter (12215): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (12215): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (12215): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (12215): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (12215): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (12215): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (12215): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (12215): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (12215): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (12215): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (12215): #17     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (12215): #18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (12215): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (12215): #20     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (12215): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)`

Here's what my doctor said (please, don't mind the Android Studio): 
`[√] Flutter (Channel master, v1.12.3-pre.45, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.12.3-pre.45 at C:\Users\hndrk\Documents\flutter_windows_v1.0.0-stable\flutter
    • Framework revision c82c587b33 (30 hours ago), 2019-11-16 18:02:51 -0500
    • Engine revision 7ef587220a
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\hndrk\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\hndrk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 78.0.3904.97
    • Web Server                • web-server    • web-javascript • Flutter Tools`

**Comment by ukeOnFire** [comment]
Sorry, should've looked further than this repo...
https://stackoverflow.com/questions/55742321/billingclient-getskudetails-failed-response-code-6
