### ISSUE TITLE
Exception in purchase listener stream

### ISSUE THREAD

**Issue by AnNEDoMini** [dooboolab/flutter_inapp_purchase#151]
### Version of flutter_inapp_purchase
2.1.0
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
No exeption
### Actual behavior
Plugin throws exception
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior
Run on device without signing in Itunes account

A bit of stacktrace. App can succesfully get prducts for purcahase, but after "Sign in into itunes account" dialog and clicking "Cancel" this happens:
```
Unhandled Exception: NoSuchMethodError: The getter 'stream' was called on null.
Receiver: null
Tried calling: stream
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      FlutterInappPurchase.purchaseUpdated (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:25:75)
#2      _BasePurchaseWidget.buyProduct (package:wot_flutter/screens/main/settings/inapp/SubscriptionsScreen.dart:129:56)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#4      _BasePurchaseWidget.buyProduct (package:wot_flutter/screens/main/settings/inapp/SubscriptionsScreen.dart:124:26)
#5      _BasePurchaseWidget.renderPurchases.<anonymous closure> (package:wot_flutter/screens/main/settings/inapp/SubscriptionsScreen.dart:180:32)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
....
```

**Comment by BinayakAdhikari** [comment]
@AnNEDoMini Did you figured it out? What was the actual issue regarding this?
