### ISSUE TITLE
Crash in Google Console

### ISSUE THREAD

**Issue by opensourcegps** [dooboolab/flutter_inapp_purchase#17]
### Version of flutter_inapp_purchase
0.5.4

### Platforms you faced the error (IOS or Android or both?)
Android

### Actual behavior
I've noticed crash in Google Play console. Crash log:

````
 java.lang.IllegalStateException:  
  at io.flutter.view.FlutterNativeView$1.reply (FlutterNativeView.java:48) 
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:14) 
  at com.dooboolab.flutterinapppurchase.FlutterInappPurchasePlugin$2.a (FlutterInappPurchasePlugin.java:6) 
  at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection.onServiceConnected (BillingClientImpl.java:93) 
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1818) 
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1847) 
  at android.os.Handler.handleCallback (Handler.java:808) 
  at android.os.Handler.dispatchMessage (Handler.java:101) 
  at android.os.Looper.loop (Looper.java:166) 
  at android.app.ActivityThread.main (ActivityThread.java:7425) 
  at java.lang.reflect.Method.invoke (Method.java) 
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245) 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
````

Code to init billilng:

````
Future<void> _billing_init() async
  {   

    try {
      _billing_prepare_result = await FlutterInappPurchase.prepare;
      print('result: '+_billing_prepare_result.toString());

      if (!mounted) return;
    }
    catch(e) {
      debugPrint('billing not available: '+e.toString());
    }


  }

 @override
  void initState() {
    super.initState();

    _billing_init();

  }

  @override
  void dispose() async{
    super.dispose();

    try {
      await FlutterInappPurchase.endConnection;
    }
    catch(e) {
    }

  }

````
Device: Huawei P10 (HWVTR), Android 8.0

Can not reproduce myself, any ideas how to debug?

**Comment by dooboolab** [comment]
@opensourcegps IAP feature won't work without `playservice` installed. Some China phones don't have `playservice` `preinstalled`, therefore, you may `alert` user when you `catched` the error to check if users installed `playservices`.

**Comment by opensourcegps** [comment]
@dooboolab I already have try/catch everywhere related to billing, however this error was logged as crash in google play console. 

https://developer.android.com/topic/performance/vitals/crash

**Comment by dooboolab** [comment]
@opensourcegps I need more information on this one to manage it. I'll get some China phone and test it myself someday.

**Comment by dooboolab** [comment]
@opensourcegps I've just released `0.5.7` fixing code that may cause the memory leak. Could you update and try again?

**Comment by opensourcegps** [comment]
Overnight 10 more reports about this crash from various phones. This is definitely not a playservice issue. I'll update to 0.5.7 today.

What about this idea:

.prepare call is run from async function.

what if .prepare call is not finished before other billing calls are executed? For example fetching purchases are executed before .prepare finished the execution.

Something like this:

````
Future<void> billing_init() async
  {   
      _billing_prepare_result = await FlutterInappPurchase.prepare;
  }

void getItems () async {
  List<IAPItem> items = await FlutterInappPurchase.getProducts(_productLists);
}

 @override
  void initState() {
    super.initState();

    billing_init();
     getItems ();
  }

````

In this case getItems() will not wait for billing_init() finish, as they both async. Can this be the reason for crashes?

**Comment by dooboolab** [comment]
@opensourcegps Oh.. ofcourse that may cause the problem because each function call is finishing asynchronously.

Why don't you wrap that in one method?
```
Future<IAPItem> get_iaps() async
  {   
      _billing_prepare_result = await FlutterInappPurchase.prepare;
     List<IAPItem> items = await FlutterInappPurchase.getProducts(_productLists);
     return items;
  }
```

**Comment by opensourcegps** [comment]
That's how it is in your plugin example. Also works on my testing devices. I'll try to modify to make sure to wait for prepare call and see if it helps.

**Comment by dooboolab** [comment]
@opensourcegps Where is it? I've differentiated all behaviors with buttons click events. If there is something like that in my example, I need to fix it. Please tell me which part.

**Comment by opensourcegps** [comment]
@dooboolab really sorry, you are right. In your example you have buttons to trigger everything. I'll change my code to wait for prepare and will follow up if it helps.

**Comment by opensourcegps** [comment]
@dooboolab to follow up on this, crashes are still going with 0.5.7 and waiting for .prepare method before running any other calls.

Same crash stack as in first message. If you have any ideas how to debug/solve this, it would be great.

**Comment by dooboolab** [comment]
@opensourcegps Feels related to [issue](https://github.com/dooboolab/flutter_inapp_purchase/issues/13). I'll try find out more.

**Comment by dooboolab** [comment]
@opensourcegps I guess this could be related to some other app that haven't closed the `billing client`. Also pasting `flutter docter` would be helpful too.

**Comment by opensourcegps** [comment]
````
[✓] Flutter (Channel master, v0.5.9-pre.41, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.9-pre.41 at /home/flutter/flutter_v0.5.1-master/flutter
    • Framework revision faffd3aef3 (3 days ago), 2018-08-15 01:01:30 -0700
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/android/sdk
    • Java binary at: /home/android/src/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/android/src/android-studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available
````

**Comment by opensourcegps** [comment]
@dooboolab just to give some ideas, please check this commit: 

"Fix on Android to queue up early requests prior billing client setup"

https://github.com/VolodymyrLykhonis/flutter_billing/commit/faf48b98e8e3b690bd98aee9a8f8c27c6d0dfc1e#diff-cdc14c9f9d8f457897ea85969400fca6


This is alternative plugin and before this fix, it was acting similar, many users could not use the plugin, however locally everything was fine. Maybe this will help with investigating this problem.

**Comment by dooboolab** [comment]
@opensourcegps This is just trying to handle the process that is still in the transaction. I don't think this is an issue with this one. Since billing service is not closed manually in this library, it may be opened forever that might miss the transaction. I think this commit was trying to manage that happening. Thank you for sharing, but I'll have to find out more about real problem-solving.

**Comment by opensourcegps** [comment]
@dooboolab thanks! I will be able to try this a bit later, because I had to urgently switch production build to the old plugin. I will try to implement in alpha/beta versions and see how it goes.

**Comment by dooboolab** [comment]
@opensourcegps FYI! I think there is fragile management in handling bridge by flutter which I could find serval issues in `flutter` repo. This will continue to improve so trying a newer version of flutter would help. Currently, I realized some managing is needed by plugin itself that flutter might have failed.

**Comment by NotThatBowser** [comment]
I came across this problem in the Play Console's Pre-launch Report too.

On the Android 8.1 test device it reported this:
```
FATAL EXCEPTION: main
Process: com.google.android.gms.ui, PID: 27855
java.lang.RuntimeException: Unable to pause activity {com.google.android.gms/com.google.android.gms.update.SystemUpdateActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean bmxc.contains(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3912)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
	at android.app.ActivityThread.-wrap15(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean bmxc.contains(java.lang.Object)' on a null object reference
	at com.google.android.gms.update.phone.SystemUpdateChimeraActivity.c(:com.google.android.gms@18385019@18.3.85 (040400-262677519):1)
	at com.google.android.gms.update.phone.SystemUpdateChimeraActivity.a(:com.google.android.gms@18385019@18.3.85 (040400-262677519):4)
	at com.google.android.gms.update.phone.SystemUpdateChimeraActivity.onPause(:com.google.android.gms@18385019@18.3.85 (040400-262677519):1)
	at com.google.android.chimera.Activity.publicOnPause(Unknown Source:0)
	at qqb.onPause(:com.google.android.gms@18385019@18.3.85 (040400-262677519):1)
	at android.app.Activity.performPause(Activity.java:7153)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
	... 11 more
```

On the Android 6.0 test device it reported this:
```
FATAL EXCEPTION: main
Process: com.wychwaystudios.rollmydice, PID: 26027
java.lang.IllegalStateException: Reply already submitted
	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply()
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error()
	at com.dooboolab.flutterinapppurchase.AndroidInappPurchasePlugin$1.onBillingServiceDisconnected()
	at com.android.billingclient.api.e$r.onServiceDisconnected()
	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1308)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1322)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5585)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by hyochan** [comment]
@NotThatBowser What version of our plugin are you using? Please specify basic information.

**Comment by NotThatBowser** [comment]
2.0.0+16

**Comment by hyochan** [comment]
Try 2.0.2 out please

**Comment by NotThatBowser** [comment]
Sorry, I had to move across to the official plugin but hopefully someone else can check this.
