### ISSUE TITLE
getSubscriptions unhandled exception (trying to save a String to List)

### ISSUE THREAD

**Issue by lukepighetti** [dooboolab/flutter_inapp_purchase#19]
Just upgraded to `v0.5.8` and get this error on `FlutterInappPurchase.getSubscriptions(skus);` under iOS. Was working perfectly on `v0.4.0`.

It appears that 

```
result = json.encode(result);

result = json.encode(result);
List list = json.decode(result.toString()); // this
```

Is returning a string.

```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'String' is not a subtype of type 'List<dynamic>'
#0      FlutterInappPurchase.getSubscriptions (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:113:24)
<asynchronous suspension>
#1      Store.getProducts (package:when_coin/services/store.dart:16:48)
<asynchronous suspension>
#2      _TestPageState._getProducts (package:when_coin/screens/store/store.dart:10:36)
#3      _TestPageState.build.<anonymous closure> (package:when_coin/screens/store/store.dart:22:30)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#17     _invoke1 (dart:ui/hooks.dart:134:13)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

```

**Comment by lukepighetti** [comment]
This is what's coming in when I get the string error
`json.decode(result.toString())`

```
[{"subscriptionPeriodNumberIOS":"1","productId":"when_coin_premium","price":"0.99","title":"Premium","subscriptionPeriodUnitIOS":"MONTH","introductoryPrice":"<SKProductDiscount: 0x1c8075fc0>","description":"Access to our coin launch sensing service","currency":"USD","localizedPrice":"$0.99"}]
```

**Comment by lukepighetti** [comment]
When I do this I get a map

`json.decode(json.decode(result.toString()))`

Lol

<img width="403" alt="screen shot 2018-08-21 at 1 27 05 pm" src="https://user-images.githubusercontent.com/666539/44418256-e8b06180-a545-11e8-8014-628c47ccac07.png">

**Comment by lukepighetti** [comment]
please consider the following starting at line 110

```
// result = json.encode(result); // delete
// result = json.encode(result); // delete

List list = json.decode(result);
```

**Comment by lukepighetti** [comment]
Does the iOS function sometimes provide a JSON encoded string and other times a list? I seem to get either depending on chance.

**Comment by dooboolab** [comment]
@lukepighetti Could you try `0.5.9`? I accidentally copied another line. Sorry for that.

**Comment by lukepighetti** [comment]
No worries, I was just playing around with it now and I kept getting stuck in Dart type hell. FWIW this is as far as I got, and its still not working for me. but I'll leave it here for posterity while I try 0.5.9

```
else if (Platform.isIOS) {
      dynamic result = await _channel.invokeMethod(
        'getItems',
        {
          'skus': skus,
        },
      );

      List<Map<dynamic, dynamic>> list = [];

      if (result.runtimeType == String)
        list = json.decode(result);
      else
        list = result;

      List<IAPItem> products = list
          .map<IAPItem>(
            (dynamic product) =>
                new IAPItem.fromJSON(product as Map<String, dynamic>),
          )
          .toList();

      return products;
    }
```

**Comment by lukepighetti** [comment]
Just went to 0.5.9 and I'm still getting the error I had while I was playing around with it. I'll keep playing around with it.

<img width="749" alt="screen shot 2018-08-21 at 2 06 48 pm" src="https://user-images.githubusercontent.com/666539/44420264-7f335180-a54b-11e8-865f-fac9ad2b1f38.png">

**Comment by dooboolab** [comment]
@lukepighetti Yeah. Converting `json` feels kind of nasty in dartlang. Need some improvement for this one. Ok I will look for the error.

**Comment by lukepighetti** [comment]
If you're coming from JS it's super nasty and I hate it.

**Comment by lukepighetti** [comment]
@dooboolab can you please tell me what type (or types) are coming through 

```
_channel.invokeMethod(
        'getItems',
        {
          'skus': skus,
        },
```

on iOS. I might be able to help. (It seems like its sometimes a list and sometimes a string?)

**Comment by lukepighetti** [comment]
I don't know why but it is working now. I will close it for now. Thank you. (Maybe I had some compiler state left over? Idk)

**Comment by dooboolab** [comment]
@lukepighetti Very strange since I am not getting the error.

**Comment by lukepighetti** [comment]
Yep. This is closed. THANK YOU!
