### ISSUE TITLE
MissingPluginException(No implementation found for method getPlatformVersion on channel flutter_inapp)

### ISSUE THREAD

**Issue by Larpoux** [dooboolab/flutter_inapp_purchase#238]
### Version of flutter_inapp_purchase
2.3.2
```sh
larpoux@iMac-de-Laurent:~/projmac/dyglot/dyglot$ flutter pub deps | grep inapp
|-- flutter_inapp_purchase 2.3.2
```

### Platforms you faced the error (IOS or Android or both?)
Android Emulator (No problems on iOS)

### Actual behavior
```
Running Gradle task 'assembleDebug'... Done                        55.3s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 3.9s
I/flutter ( 4550): No filters!
E/flutter ( 4550): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel flutter_inapp)
E/flutter ( 4550): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 4550): <asynchronous suspension>
E/flutter ( 4550): #1      FlutterInappPurchase.platformVersion (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:60:28)
E/flutter ( 4550): <asynchronous suspension>
E/flutter ( 4550): #2      initPlatformState (package:dyglot/globals.dart:179:35)
E/flutter ( 4550): <asynchronous suspension>
E/flutter ( 4550): #3      initGlobals (package:dyglot/globals.dart:167:9)
E/flutter ( 4550): <asynchronous suspension>
E/flutter ( 4550): #4      HomeView.initState.<anonymous closure>.<anonymous closure> (package:dyglot/home_form.dart:74:41)
E/flutter ( 4550): <asynchronous suspension>
E/flutter ( 4550): #5      busy (package:dyglot/globals.dart:423:9)
E/flutter ( 4550): <asynchronous suspension>
E/flutter ( 4550): 
Waiting for Android SDK built for x86 64 to report its views...         21ms
Syncing files to device Android SDK built for x86 64...            181ms
```

### Tested environment (Emulator? Real Device?)
Emulator API 28

**Comment by hyochan** [comment]
Hey~ my friend! This is very strange. Let me look into this soon.

**Comment by Larpoux** [comment]
Hi Hyo,

There is no urgency for me, as I actually do not work on Dyglot project.
I am currently working on Flutter Sound on Flutter Web.
Most of the work is done. I will release Flutter Sound 6.4 probably at the end of the week.

**Comment by mgonzalezc** [comment]
Hello! Can you please check if my pull request https://github.com/dooboolab/flutter_inapp_purchase/pull/239 works for you?

I found the same error some time ago, and completely forgot about doing a pull request

**Comment by Larpoux** [comment]
@mgonzalezc 

I am back on my Dyglot Project and I do not have anymore problems for building installing and running my App.
Software Science is black magic.

Thank you to all of you for contributing to Free and Open Source software
