### ISSUE TITLE
Crashes on Fire Tablet with NoSuchMethodError 

### ISSUE THREAD

**Issue by arisbartee** [dooboolab/flutter_inapp_purchase#242]
### Deploy Android app to Fire Tablet and  call FlutterInappPurchase.instance.initConnection.

Fatal Exception: java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles()Ljava/lang/String; in class Lcom/android/billingclient/api/SkuDetails; or its super classes (declaration of 'com.android.billingclient.api.SkuDetails' appears in base.apk!classes2.dex)
       at com.dooboolab.flutterinapppurchase.AndroidInappPurchasePlugin$3.onSkuDetailsResponse(AndroidInappPurchasePlugin.java:227)
       at com.android.billingclient.api.zzac.run(com.android.billingclient:billing@@3.0.1:8)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6740)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by arisbartee** [comment]
I discovered that because I side loaded the Google Play Store, the library was detecting that the Play Store was installed.
