### ISSUE TITLE
Not receiving products on iOS

### ISSUE THREAD

**Issue by gildaswise** [dooboolab/flutter_inapp_purchase#32]
### Version of flutter_inapp_purchase
0.6.5

### Platforms you faced the error (iOS or Android or both?)
iOS

### Expected behavior
Receiving product as an IAPItem

### Actual behavior
Not receiving anything

### Tested environment (Emulator? Real Device?)
Both emulador and real device

### Steps to reproduce the behavior
Call `getProducts` with the desired product IDs

### Other info
I'm using TestFlight with this app and already registered an IAP there, its status is Waiting for Review and I've already checked with @lukepighetti that his IAP worked even with this status.

Also, neither `catchError` or `try/catch` block are working on this code I'm using:

```Dart
 Future<List<IAPItem>> refreshProducts({bool includeTests = false}) async {
    final items = skus.values.toList();
    if (includeTests && _platformVersion.contains("Android"))
      items.addAll(_tests);
    Logger.log(TAG,
        message: "Requesting ${items.length} SKUs: ${items.toString()}");
    List<IAPItem> products = [];
    try {
      await FlutterInappPurchase.getProducts(items)
          .catchError((exception, stacktrace) {
        Logger.log(TAG,
            message:
                "Couldn't refresh products, error: $exception, $stacktrace");
      }).then(products.addAll);
    } catch (error) {
      Logger.log(TAG, message: "Couldn't refresh products: $error");
    }
    Logger.log(TAG, message: "Got: ${products?.length} products");
    if (products != null && products.isNotEmpty) {
      _availableProducts.clear();
      _availableProducts.addAll(products);
    }
    return _availableProducts;
  }
```

**Comment by dooboolab** [comment]
@gildaswise You should use the whole name com.product.product.allitems .
I hope you take a look at the product detail on App Store connect (iTunes connect).
Check the contract info and fill the right info. This function is well tested, and always have been tested. And testable in simulator.
Please refer to the example project, also.

**Comment by lukepighetti** [comment]
Here is all of my code for IAP for subscriptions. Maybe it's helpful. This is everything.

```dart
class Store {
  static Store _instance = new Store();
  static Store get instance => _instance;
  static String sku = 'when_coin_premium';

  static setup() async {
    await FlutterInappPurchase.prepare;
    final bool isSubscribed = await checkSubscribed();
    _saveToFirebase(isSubscribed);
    FlutterInappPurchase.endConnection;
  }

  static Future<bool> subscribe() async {
    try {
      await FlutterInappPurchase.prepare;
      await FlutterInappPurchase.getSubscriptions([sku]);
      await FlutterInappPurchase.buySubscription(sku);
      FlutterInappPurchase.endConnection;
      await _saveToFirebase(true);
      return true;
    } catch (e) {
      return false;
    }
  }

  static Future<bool> checkSubscribed() async {
    bool isSubscribed = await FlutterInappPurchase.checkSubscribed(
      sku: sku,
      duration: Duration(minutes: 5),
      grace: Duration(minutes: 1),
    );

    await _saveToFirebase(isSubscribed);
    return isSubscribed;
  }

  static Future<void> _saveToFirebase(bool isSubscribed) =>
      User.instance.ref.child('subscribed').set(isSubscribed ?? false);
}
```

**Comment by RobertBrunhage** [comment]
My code is working on Android so would be weird that it wouldn't be working on IOS.

**Comment by gildaswise** [comment]
I tried calling `buyProduct` without calling `getProducts` before and finally got an error:

```
[PURCHASE_MANAGER] Couldn't buy product, error: PlatformException(E_DEVELOPER_ERROR, Invalid product ID., null)
```

But I called `buyProduct` with the _exact_ `productId` that is on App Store Connect's In-App Purchases section, it doesn't make sense.

**Comment by dooboolab** [comment]
@gildaswise Could you check [issue](https://github.com/dooboolab/react-native-iap/issues/170) and [issue](https://github.com/dooboolab/react-native-iap/issues/204) here? Also did you complete the `Agreements, Tax and Banking` in `itunesconnect`?

**Comment by gildaswise** [comment]
Finished `Agreements, Tax and Banking` and `getProducts` is finally working, but now I'm receiving this error on `buyProduct`:

```
[PURCHASE_MANAGER] Couldn't buy product, error: PlatformException(E_UNKNOWN, An unknown or unexpected error has occured. Please try again later., null), stacktrace: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
<asynchronous suspension>
#2      FlutterInappPurchase.buyProduct (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:212:12)
```

**Comment by RobertBrunhage** [comment]
@gildaswise Did you have to wait for the Agreements, Tax and Banking status to be done or can you fetch products when it is pending?

**Comment by gildaswise** [comment]
@RobertBrunhage I had to click `Request` on the `Paid Applications` contract and then fill all forms (except for the AUS' tax info one). A few minutes later, I could get `getProducts` working, but I still can't finish the IAP with `buyProduct`.

**Comment by gildaswise** [comment]
Update: it worked now (maybe it had a delay?) on a physical device (iPhone 7+), but nothing on the Simulator yet.

**Comment by lukepighetti** [comment]
Payment test and notifications are physical device only on iOS
