### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by eliseyOzerov** [dooboolab/flutter_inapp_purchase#366]
### Version of flutter_inapp_purchase

5.2.0

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

App launches normally

### Actual behavior

Exception crashes app shortly after the launch screen is shown

```
Launching lib/main.dart on SM G965F in debug mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterJNI( 5612): FlutterJNI.loadLibrary called more than once
W/FlutterJNI( 5612): FlutterJNI.prefetchDefaultFontManager called more than once
W/FlutterJNI( 5612): FlutterJNI.init called more than once
D/AndroidRuntime( 5612): Shutting down VM
E/AndroidRuntime( 5612): FATAL EXCEPTION: main
E/AndroidRuntime( 5612): Process: com.swybrand.app, PID: 5612
E/AndroidRuntime( 5612): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 5612): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/AndroidRuntime( 5612): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime( 5612): 	at com.dooboolab.flutterinapppurchase.MethodResultWrapper$1.run(MethodResultWrapper.java:27)
E/AndroidRuntime( 5612): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 5612): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 5612): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 5612): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime( 5612): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5612): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime( 5612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/Process ( 5612): Sending signal. PID: 5612 SIG: 9
Lost connection to device.
Exited
```

### Tested environment (Emulator? Real Device?)

Samsung S9+

### Steps to reproduce the behavior

Launch the app

**Comment by soarescaique** [comment]
There is an open PR #365  that fixes this issue
