### ISSUE TITLE
localizedPrice & price is null on Android

### ISSUE THREAD

**Issue by english-aha-center** [dooboolab/flutter_inapp_purchase#416]
Hi, first of all thanks for this amazing package. 
I am having an issue with localizedPrice & price being null after upgrading Flutter version from 3.3.1 to 3.7.5. Prices are setup correctly in Play Store. Previous version of the app behaves correctly on production that is built with Flutter version 3.3.1

### Version of flutter_inapp_purchase: 
- 5.0.4 (tried with the latest version 5.4.1, still null value)

### Platforms you faced the error: 
- Android

### Expected behavior: 
- localizedPrice & price should not be null on Android

### Actual behavior
- localizedPrice & price is null on Android

### Tested environment: 
- Real Device

### Steps to reproduce the behavior: 
FlutterInappPurchase.instance.getProducts(_productLists)

**Comment by edscodeblenders** [comment]
I'm having the same issue, any news about this?

**Comment by deakjahn** [comment]
Probabla this error? https://github.com/dooboolab-community/flutter_inapp_purchase/pull/392

**Comment by KzumO36** [comment]
Any assistance? This is a breaking issue guys, help would be appreciated. Tried to downgrade down to 4.0.0 but still, its all null now.

**Comment by deakjahn** [comment]
@KzumO36 not really. It would be nice to have it fixed, sure, but you can simply use:

    var price = product.localizedPrice ?? product.introductoryPrice;

**Comment by KzumO36** [comment]
No, theres still an exception then. It's showing the price yes but if you tap on an item to buy it, theres still an error.

`E/flutter (17774): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(InappPurchasePlugin, buyItemByType, null, null)
E/flutter (17774): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (17774): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter (17774): <asynchronous suspension>
E/flutter (17774): #2      FlutterInappPurchase.requestPurchase (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:278:14)
E/flutter (17774): <asynchronous suspension>`

**Comment by deakjahn** [comment]
@KzumO36 That's a different problem, unrelated to the price display. I happened to have fixed it a few days ago. :-) See https://github.com/dooboolab-community/flutter_inapp_purchase/pull/423, it will be merged soon, hopefully, but until then, just fix it for yourself. It works, I already have my modified app in the store successfully.

**Comment by KzumO36** [comment]
@deakjahn I have used your repo now and it works, thank you!

**Comment by pabbathiharish** [comment]
@KzumO36  I am also getting same Exception , Any Update on this.

**Comment by moodstubos** [comment]
this seems to be related: https://github.com/dooboolab-community/flutter_inapp_purchase/issues/430

Workaround works for me.

**Comment by deakjahn** [comment]
@RomanSoviak Your decision, but 1) the other plugin is far from being equivalent, it lacks important features that this one supports, 2) this error has already been fixed.
